version: '3.8'
services:
  db:
    container_name: db
    hostname: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes: 
      # - ./postgres:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=employees
    networks:
      - mynetwork

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DB_HOST=db


networks:
  mynetwork:
